apiVersion: v1
kind: Secret
metadata:
  name: cqrssecrets
data:
  AzureWebJobsStorage: {{.Values.AzureWebJobsStorage}}       
  FUNCTIONS_WORKER_RUNTIME: ZG90bmV0                
  EVENTHUB_CONNECTIONSTRING: {{.Values.EVENTHUB_CONNECTIONSTRING}}  
  APPINSIGHTS_INSTRUMENTATIONKEY: {{.Values.APPINSIGHTS_INSTRUMENTATIONKEY}}
  SEARCH_SERVICENAME: {{.Values.SEARCH_SERVICENAME}}
  SEARCH_ADMINKEY: {{.Values.SEARCH_ADMINKEY}}
  SEARCH_INDEXNAME: {{.Values.SEARCH_INDEXNAME}}