apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  namespace: default
  labels:
    app: cqrsapi
    component: api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: cqrsapi
        component: api
        lang: golang
    spec:
      containers:
      - name: aeskeyapi
        image: acrqglgusxw001.azurecr.io/cqrs/api:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        envFrom:
        - secretRef:
            name: cqrssecrets
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: "0.5"
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: cqrsapisvc
  labels:
    version: "1.5"
spec:
  selector:
    app: cqrsapi
  ports:
  - port: 8081
    targetPort: 8081
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cqrsapi
spec:
  rules:
  - http: 
      paths: 
      - backend:
          serviceName: cqrsapisvc
          servicePort: 8081
        path: /