apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: eventprocessor
  name: eventprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventprocessor
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: eventprocessor
    spec:
      containers:
      - env:
        - name: AzureFunctionsJobHost__functions__0
          value: CommandProcessing
        envFrom:
        - secretRef:
            name: eventprocessor
        image: bjd145.azurecr.io/cqrs/eventprocessor
        imagePullPolicy: Always
        name: eventprocessor
        resources: {}
      restartPolicy: Always
