---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventprocessor
  namespace: default
  labels:
    app: eventprocessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventprocessor
  template:
    metadata:
      labels:
        app: eventprocessor
    spec:
      containers:
      - name: eventprocessor
        image: acrqglgusxw001.azurecr.io/cqrs/eventprocessor:1.0
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: CommandProcessing
        envFrom:
        - secretRef:
            name: cqrssecrets
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.5"
            memory: 128Mi
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: eventprocessor
  namespace: default
  labels:
    deploymentName: eventprocessor
spec:
  scaleTargetRef:
    deploymentName: eventprocessor
  minReplicaCount: 0
  maxReplicaCount: 20
  pollingInterval: 15
  triggers:
  - type: azure-eventhub
    metadata:
      type: eventHubTrigger
      connection: EVENTHUB_CONNECTIONSTRING
      eventHubName: events
      name: events
      unprocessedEventThreshold: "25"
      
